name: muvam
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  country_picker: ^2.0.26

  # State & Utilities
  provider: ^6.1.2
  logger: ^2.6.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2

  # Networking & Storage
  http: ^1.2.1
  shared_preferences: ^2.2.3
  web_socket_channel: ^2.4.0

  # Location & Maps
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.9

  # Media & Launchers
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
