name: muvam
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_picker: ^2.0.26
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.2.4
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  flutter_svg: ^2.2.3
  logger: ^2.6.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
